from distutils.core import setup

setup(
    name='Project Skittles',
    version='0.1',
    packages=['env.lib.python3.4.distutils', 'env.lib.python3.4.encodings', 'env.lib.python3.4.importlib',
              'env.lib.python3.4.collections', 'env.lib.python3.4.site-packages.pip',
              'env.lib.python3.4.site-packages.pip.req', 'env.lib.python3.4.site-packages.pip.vcs',
              'env.lib.python3.4.site-packages.pip.utils', 'env.lib.python3.4.site-packages.pip.compat',
              'env.lib.python3.4.site-packages.pip.models', 'env.lib.python3.4.site-packages.pip._vendor',
              'env.lib.python3.4.site-packages.pip._vendor.distlib',
              'env.lib.python3.4.site-packages.pip._vendor.distlib._backport',
              'env.lib.python3.4.site-packages.pip._vendor.colorama',
              'env.lib.python3.4.site-packages.pip._vendor.html5lib',
              'env.lib.python3.4.site-packages.pip._vendor.html5lib.trie',
              'env.lib.python3.4.site-packages.pip._vendor.html5lib.filters',
              'env.lib.python3.4.site-packages.pip._vendor.html5lib.serializer',
              'env.lib.python3.4.site-packages.pip._vendor.html5lib.treewalkers',
              'env.lib.python3.4.site-packages.pip._vendor.html5lib.treeadapters',
              'env.lib.python3.4.site-packages.pip._vendor.html5lib.treebuilders',
              'env.lib.python3.4.site-packages.pip._vendor.lockfile',
              'env.lib.python3.4.site-packages.pip._vendor.progress',
              'env.lib.python3.4.site-packages.pip._vendor.requests',
              'env.lib.python3.4.site-packages.pip._vendor.requests.packages',
              'env.lib.python3.4.site-packages.pip._vendor.requests.packages.chardet',
              'env.lib.python3.4.site-packages.pip._vendor.requests.packages.urllib3',
              'env.lib.python3.4.site-packages.pip._vendor.requests.packages.urllib3.util',
              'env.lib.python3.4.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'env.lib.python3.4.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'env.lib.python3.4.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'env.lib.python3.4.site-packages.pip._vendor.packaging',
              'env.lib.python3.4.site-packages.pip._vendor._markerlib',
              'env.lib.python3.4.site-packages.pip._vendor.cachecontrol',
              'env.lib.python3.4.site-packages.pip._vendor.cachecontrol.caches',
              'env.lib.python3.4.site-packages.pip._vendor.pkg_resources',
              'env.lib.python3.4.site-packages.pip._vendor.pkg_resources.tests',
              'env.lib.python3.4.site-packages.pip.commands', 'env.lib.python3.4.site-packages.pip.operations',
              'env.lib.python3.4.site-packages.wheel', 'env.lib.python3.4.site-packages.wheel.test',
              'env.lib.python3.4.site-packages.wheel.test.simple.dist.simpledist',
              'env.lib.python3.4.site-packages.wheel.test.complex-dist.complexdist',
              'env.lib.python3.4.site-packages.wheel.tool', 'env.lib.python3.4.site-packages.wheel.signatures',
              'env.lib.python3.4.site-packages._markerlib', 'env.lib.python3.4.site-packages.setuptools',
              'env.lib.python3.4.site-packages.setuptools.command', 'env.lib.python3.4.site-packages.pkg_resources',
              'env.lib.python3.4.site-packages.pkg_resources._vendor',
              'env.lib.python3.4.site-packages.pkg_resources._vendor.packaging'],
    url='http://www.sandervankasteel.nl/skittles',
    license='GNU GPL/v2',
    author='Sander van Kasteel',
    author_email='info@sandervankasteel.nl',
    description='Miauw!'
)
